project:
  type: website
  render:
    - "*.ipynb"

website:
  title: "데이터 사이언스 스쿨 - 파이썬"
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "소개의 글"
        href: "00.00 소개의 글.ipynb"
      - section: "1장 파이썬 설치와 설정"
        href: "01.00 1장 파이썬 설치와 설정.ipynb"
        contents:
          - "01.01 파이썬 설치하기.ipynb"
          - "01.02 파이썬 처음 사용하기.ipynb"
          - "01.03 파이썬 패키지 설치하기.ipynb"
          - "01.04 데이터 분석용 파이썬 패키지 소개.ipynb"
          - "01.05 아이파이썬 및 주피터 설정.ipynb"

format:
  html:
    toc: true
    code-block-bg: true
